name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: spivanatalie64/.github/.github/workflows/ci-guile.yml@main
    with:
      module-name: "yacfs_metrics"
